//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationHistory
    {
        public int HistoryID { get; set; }
        public int ApplicationID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ChangedByUserID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
    }
}
