//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.ApplicationHistories = new HashSet<ApplicationHistory>();
            this.Appointments = new HashSet<Appointment>();
            this.Documents = new HashSet<Document>();
            this.Passports = new HashSet<Passport>();
        }
    
        public int ApplicationID { get; set; }
        public string ApplicationNumber { get; set; }
        public int CitizenID { get; set; }
        public int PassportTypeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public string ApplicationType { get; set; }
        public string PreviousPassportNumber { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string TravelPurpose { get; set; }
        public Nullable<System.DateTime> ExpectedTravelDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<System.DateTime> RejectedAt { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationHistory> ApplicationHistories { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual Office Office { get; set; }
        public virtual PassportType PassportType { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passport> Passports { get; set; }
    }
}
