//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int ApplicationID { get; set; }
        public int OfficeID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string TimeSlot { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Office Office { get; set; }
    }
}
