//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public int ApplicationID { get; set; }
        public int DocumentTypeID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string MimeType { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<int> VerifiedByUserID { get; set; }
        public Nullable<System.DateTime> VerifiedAt { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual User User { get; set; }
    }
}
