//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int PassportID { get; set; }
        public string PassportNumber { get; set; }
        public int ApplicationID { get; set; }
        public int CitizenID { get; set; }
        public int PassportTypeID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> IssuingOfficeID { get; set; }
        public string Status { get; set; }
        public string MRZLine1 { get; set; }
        public string MRZLine2 { get; set; }
        public Nullable<System.DateTime> PrintedAt { get; set; }
        public Nullable<System.DateTime> CollectedAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual Office Office { get; set; }
        public virtual PassportType PassportType { get; set; }
    }
}
