//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PassportEntities : DbContext
    {
        public PassportEntities()
            : base("name=PassportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationHistory> ApplicationHistories { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatuses { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<Citizen> Citizens { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<PassportType> PassportTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
    
        public virtual ObjectResult<SP_RegisterUser_WithJWT_Result> SP_RegisterUser_WithJWT(string fullName, string email, string loginID, byte[] passwordHash, byte[] passwordSalt, string nationality, string jwtToken, Nullable<int> tokenExpiryMinutes)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var loginIDParameter = loginID != null ?
                new ObjectParameter("LoginID", loginID) :
                new ObjectParameter("LoginID", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(byte[]));
    
            var passwordSaltParameter = passwordSalt != null ?
                new ObjectParameter("PasswordSalt", passwordSalt) :
                new ObjectParameter("PasswordSalt", typeof(byte[]));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(string));
    
            var jwtTokenParameter = jwtToken != null ?
                new ObjectParameter("JwtToken", jwtToken) :
                new ObjectParameter("JwtToken", typeof(string));
    
            var tokenExpiryMinutesParameter = tokenExpiryMinutes.HasValue ?
                new ObjectParameter("TokenExpiryMinutes", tokenExpiryMinutes) :
                new ObjectParameter("TokenExpiryMinutes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RegisterUser_WithJWT_Result>("SP_RegisterUser_WithJWT", fullNameParameter, emailParameter, loginIDParameter, passwordHashParameter, passwordSaltParameter, nationalityParameter, jwtTokenParameter, tokenExpiryMinutesParameter);
        }
    
        public virtual ObjectResult<SP_RegisterOrLoginUser_Result> SP_RegisterOrLoginUser(string mode, string loginID, byte[] passwordHash, byte[] salt, string fullName, string emailAddress, string registrationType, string jwtToken, Nullable<int> tokenExpiryMinutes)
        {
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            var loginIDParameter = loginID != null ?
                new ObjectParameter("LoginID", loginID) :
                new ObjectParameter("LoginID", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(byte[]));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(byte[]));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var registrationTypeParameter = registrationType != null ?
                new ObjectParameter("RegistrationType", registrationType) :
                new ObjectParameter("RegistrationType", typeof(string));
    
            var jwtTokenParameter = jwtToken != null ?
                new ObjectParameter("JwtToken", jwtToken) :
                new ObjectParameter("JwtToken", typeof(string));
    
            var tokenExpiryMinutesParameter = tokenExpiryMinutes.HasValue ?
                new ObjectParameter("TokenExpiryMinutes", tokenExpiryMinutes) :
                new ObjectParameter("TokenExpiryMinutes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RegisterOrLoginUser_Result>("SP_RegisterOrLoginUser", modeParameter, loginIDParameter, passwordHashParameter, saltParameter, fullNameParameter, emailAddressParameter, registrationTypeParameter, jwtTokenParameter, tokenExpiryMinutesParameter);
        }
    }
}
