//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passsport
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public int TokenID { get; set; }
        public int UserID { get; set; }
        public string JwtToken { get; set; }
        public System.DateTime IssuedAt { get; set; }
        public System.DateTime ExpiryAt { get; set; }
        public Nullable<bool> IsRevoked { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
